language: C
dist: trusty
sudo: true

env:
  - RELEASE_VERSION=$(wget -q "https://ftp.gnu.org/pub/gnu/emacs/?C=M;O=D" -O - | grep -oe ">emacs-.*tar.gz" | head -n 1 | cut -d - -f 2 | sed -e 's|.tar.gz||g')
  
script:
  - wget -c "http://ftpmirror.gnu.org/emacs/emacs-${RELEASE_VERSION}.tar.gz"
  - tar xf emacs-*tar.gz
  - cd emacs*
  - sudo apt-get build-dep emacs24
  - sudo apt-get -y install libgtk-3-dev libwebkitgtk-3.0-dev
  - ./autogen.sh
  - ./configure --prefix=/app --without-selinux --with-x-toolkit=gtk3
  - make -j$(nproc)
  - sudo make install
  - cd ..
#  - sudo apt-get -y install squashfs-tools
  - bash -ex appimage.sh
  
after_success:
  - ls -lh ../../out/* # Assuming you have some files in out/ that you would like to upload
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ../../out/*AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
